import java.util.HashMap;
import org.json.JSONObject;
import java.util.Date; 
import java.util.Calendar; 
import java.text.SimpleDateFormat; 
import com.satimetry.nudge.Output;

global java.util.HashMap output;
global SimpleDateFormat inSDF;
global SimpleDateFormat outSDF;

function void print(String txt) {
   System.out.println(txt);
}

// Declare inside drl so we can manipulate objects naturally
declare Participant
  @role( fact )
  id : String @key
  gastype : String
  dayofweek : String
end

// Declare inside drl so we can manipulate objects naturally
declare Observation
  @role( event )
  @timestamp ( obsdate )
  id : String @key
  obsdate : Date @key
  obsvalue : Integer
  obsdiff : Integer
end

rule "ruleInsertObservation"
  salience 2000
  when
    $input : JSONObject() from entry-point DEFAULT 
  then
//    inSDF = new SimpleDateFormat("yyyy-M-d H:m:s Z");
//    Date date = inSDF.parse( $input.get("obsdate").toString() + " +1100" );
    inSDF = new SimpleDateFormat("yyyy-M-d H:m:s");
    Date date = inSDF.parse( $input.get("obsdate").toString() + "" );

    Calendar calendar = Calendar.getInstance();
    calendar.setTime(date);
    int hour = calendar.get(Calendar.HOUR) + 1;
    int minute = calendar.get(Calendar.MINUTE);
    int second = calendar.get(Calendar.SECOND);
    Observation obs = new Observation($input.get("username").toString(), date);
    obs.setObsvalue( Integer.parseInt($input.get("obsvalue").toString()) );
    obs.setObsdiff( Math.abs ( (hour*60) + minute - (8*60) ) );
    insert(obs);
print(hour + " " + minute);
    print(drools.getRule().getName() + "->" + obs.getId() + "-" + obs.getObsdate() + "-" + obs.getObsvalue() + "-" + obs.getObsdiff() );
end

rule "ruleInsertParticipant"
  salience 1000
  when
    $input : JSONObject() from entry-point DEFAULT 
    not Participant( id == $input.get("username").toString() )
  then
    Date today = new Date();
    String dayofweek = new SimpleDateFormat("EE").format(today);
    Participant $participant = new Participant( $input.get("username").toString() );
    $participant.setGastype( $input.get("obsname").toString() );
    $participant.setDayofweek(dayofweek);
    insert( $participant );
    print(drools.getRule().getName() + "->" + $participant.getId() + "-" + $participant.getGastype() );
end

rule "ruleMedicationCount"
  salience -100
  no-loop true
  when
    $participant : Participant()
    $obsCountTotal : Number( intValue > 0) from accumulate(
      Observation( $obsCount : obsvalue > 0, $participant.id == id ) over window:time( 41d ),
      count( $obsCount ) )
  then
    Date today = new Date();

    java.util.Date date = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String datef = sdf.format( date );

    JSONObject joutput = new JSONObject();
    joutput.put("id", $participant.getId());
    joutput.put("rulename", drools.getRule().getName());
    joutput.put("ruledate", datef);
    joutput.put("rulemsg", "You took your medication " + $obsCountTotal + " times in the past 14 days.");
		joutput.put("ruledata", "http://www.thenudgemachine.com/msg.php");
    Output $output = new Output(joutput.toString());
    insert($output);
   	print(drools.getRule().getName() + "->" + $participant.getId() + " - " + $participant.getDayofweek() );
end

rule "ruleMedicationTime"
  salience -100
  no-loop true
  when
    $participant : Participant()
    $obsCountTotal : Number( intValue > 0) from accumulate(
      Observation( $obsCount : obsdiff > 60, $participant.id == id ) over window:time( 41d ),
      count( $obsCount ) )
  then
    Date today = new Date();

    java.util.Date date = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String datef = sdf.format( date );

    JSONObject joutput = new JSONObject();
    joutput.put("id", $participant.getId());
    joutput.put("rulename", drools.getRule().getName());
    joutput.put("ruledate", datef);
    joutput.put("rulemsg", "You took your medication more than 1 hour from suggested time " + $obsCountTotal + " times in the past 14 days.");
		joutput.put("ruledata", "http://www.thenudgemachine.com/msg.php");
    Output $output = new Output(joutput.toString());
    insert($output);
    print(drools.getRule().getName() + "->" + $participant.getId() + " - " + $participant.getDayofweek() );
end

rule "ruleMedicationFullAdherance"
  salience -100
  no-loop true
  when
    $participant : Participant()
    $obsCountTotal : Number( intValue > 0) from accumulate(
      Observation( $obsCount : obsvalue == 2 && obsdiff < 60, $participant.id == id ) over window:time( 41d ),
      count( $obsCount ) )
  then
    Date today = new Date();

    java.util.Date date = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String datef = sdf.format( date );

    JSONObject joutput = new JSONObject();
    joutput.put("id", $participant.getId());
    joutput.put("rulename", drools.getRule().getName());
    joutput.put("ruledate", datef);
    joutput.put("rulemsg", "You fully complied with your medication schedule " + $obsCountTotal + " times in the past 14 days.");
    joutput.put("ruledata", "http://www.thenudgemachine.com/msg.php");
    Output $output = new Output(joutput.toString());
    insert($output);
    print(drools.getRule().getName() + "->" + $participant.getId() + " - " + $participant.getDayofweek() );
end


rule "ruleMedicationPartialAdherance"
  salience -100
  no-loop true
  when
    $participant : Participant()
    $obsCountTotal : Number( intValue > 0) from accumulate(
      Observation( $obsCount : obsvalue == 2, $participant.id == id ) over window:time( 41d ),
      count( $obsCount ) )
  then
    Date today = new Date();

    java.util.Date date = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String datef = sdf.format( date );

    JSONObject joutput = new JSONObject();
    joutput.put("id", $participant.getId());
    joutput.put("rulename", drools.getRule().getName());
    joutput.put("ruledate", datef);
    joutput.put("rulemsg", "You partially complied with your medication schedule " + $obsCountTotal + " times in the past 14 days.");
    joutput.put("ruledata", "http://www.thenudgemachine.com/msg.php");
    Output $output = new Output(joutput.toString());
    insert($output);
    print(drools.getRule().getName() + "->" + $participant.getId() + " - " + $participant.getDayofweek() );
end


